"""A cached Ivy's Read with a null fact that the stores now serve is stale: not served, regenerated by the warm."""
import json

import pytest

from app.services.options_read_gate import (
    FACT_VALUE_KEYS, SERVABLE_GROUPS, cache_key, format_facts, load_cached_read, load_cached_read_status,
    stale_facts, stale_reason,
)

SYM, CHAIN = "SNPS", "2026-09-21"


def _block(**over):
    v = {k: None for k in FACT_VALUE_KEYS}
    v.update({"current_price": 430.0, "chain_date": CHAIN, "atm_iv": 0.52, "rv_sample_days": 0,
              "expected_move_pct": 0.06, "earnings_sample_size": 0})
    v.update(over)
    return v


def _store(block):
    payload = json.dumps({"content": "prose", "facts": {}, "fact_values": block, "model_used": "m", "generated_at": "t"})
    async def get_meta(key):
        return payload if key == cache_key(SYM, CHAIN) else None
    return get_meta


def test_stale_facts_names_the_null_facts_whose_group_is_servable():
    block = _block(rv_reason="Realized volatility could not be computed reliably for this ticker")
    assert stale_facts(block, {"rv": True, "atm_iv": True, "earnings_history": False}) == list(SERVABLE_GROUPS["rv"])
    assert stale_facts(block, {"rv": False, "atm_iv": True, "earnings_history": False}) == []
    assert stale_facts(block, {"rv": True, "atm_iv": True, "earnings_history": True}) == list(SERVABLE_GROUPS["rv"]) + ["avg_earnings_1d_move_pct"]
    assert stale_facts(_block(rv_20d=0.65, rv_rank=27.8, rv_percentile=30.0, rv_min_1y=0.2, rv_max_1y=0.9), {"rv": True}) == []
    assert stale_facts(None, {"rv": True}) == [] and stale_facts(block, None) == []


@pytest.mark.asyncio
async def test_cached_read_with_null_rv_is_not_served_once_rv_is_servable():
    logs: list[str] = []
    get_meta = _store(_block(rv_reason="Realized volatility could not be computed reliably for this ticker"))
    # RV still unavailable: the read is served as it was written
    data, stale = await load_cached_read_status(get_meta, SYM, CHAIN, True, {"rv": False, "atm_iv": True}, log=logs.append)
    assert data is not None and stale is None
    # RV servable now: stale, not served, the trigger fact logged
    data, stale = await load_cached_read_status(get_meta, SYM, CHAIN, True, {"rv": True, "atm_iv": True}, log=logs.append)
    assert data is None and stale == "rv_20d"
    assert logs and "rv_20d is null in its fact block but servable now" in logs[-1]
    assert await load_cached_read(get_meta, SYM, CHAIN, True, {"rv": True}) is None
    # without a servability map (the /explain consumer) the read is served as before
    assert await load_cached_read(get_meta, SYM, CHAIN, True) is not None


def test_stale_reason_is_plain_language():
    assert stale_reason("rv_20d") == ("Ivy's Read was written when realized volatility was unavailable and is being "
                                      "regenerated now that it is")
    assert "implied volatility" in stale_reason("atm_iv")


def test_fact_value_keys_round_trip_rv_reason_and_date_into_the_prompt_strings():
    assert "rv_reason" in FACT_VALUE_KEYS and "rv_as_of" in FACT_VALUE_KEYS
    reason = "Realized volatility could not be computed reliably for this ticker"
    block = _block(rv_reason=reason, rv_as_of=None)
    facts = format_facts(SYM, "Synopsys", block)
    assert facts["realized_vol_20d"] == f"(unavailable: {reason})"      # prose and rows state the same reason
    assert facts["rv_as_of"] == "(unavailable)"
    served = _block(rv_20d=0.6523, rv_rank=27.8, rv_percentile=30.0, rv_min_1y=0.2, rv_max_1y=0.9, rv_as_of="2026-09-22")
    facts = format_facts(SYM, "Synopsys", served)
    assert facts["realized_vol_20d"] == "65.2%" and facts["rv_as_of"] == "2026-09-22"
    # every key survives a JSON round trip unchanged
    assert set(json.loads(json.dumps(served))) == set(FACT_VALUE_KEYS)


def test_endpoint_uses_the_servable_rv_and_the_status_loader():
    from pathlib import Path
    src = Path(__file__).resolve().parents[1].joinpath("app/routers/tickers.py").read_text()
    region = src[src.index('@router.get("/options-read/{symbol}"'):src.index("ExplainMetric = ")]
    assert "get_servable_rv(db, sym)" in region and "get_latest_rv(" not in region
    assert "load_cached_read_status(" in region and "regenerated_for=stale_fact" in region
    assert '"rv_reason": rv_reason' in region
