import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclosures | Alert Interface",
};

const sections = [
  {
    heading: "Not investment advice",
    body: `Alert Interface is an independent research and educational tool. Nothing on this site is personalized investment advice, and nothing here considers your financial situation, objectives, or risk tolerance. Ivy's picks and Build a Trade drafts are generated by software from public data and are published to every visitor identically. You alone are responsible for any decision to trade.`,
  },
  {
    heading: "Hypothetical performance",
    body: `Ivy's ledger tracks picks that were generated and recorded but never executed. Settled and open P&L are computed from published option prices at entry and at settlement or the latest mark. They do not include commissions, fees, slippage, bid-ask spread costs, assignment, or early exercise, and a real trade would not have filled at these prices. Hypothetical results have inherent limitations and past results do not indicate future results.`,
  },
  {
    heading: "Options involve substantial risk",
    body: `Options are not suitable for all investors. You can lose the entire amount paid for an option or spread, and some strategies carry unlimited risk. Before trading options, read Characteristics and Risks of Standardized Options, published by the Options Clearing Corporation:`,
    link: {
      href: "https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document",
      label: "Options Disclosure Document (OCC)",
    },
  },
  {
    heading: "Data and AI-generated content",
    body: `Price and option data come from third-party providers and may be delayed, incomplete, or wrong. Reference data (earnings history, analyst actions, volatility) refreshes nightly. Research notes are written by an AI model and checked by a second model against source filings; the check reduces errors but does not eliminate them. Verify anything material against the primary source.`,
  },
  {
    heading: "No relationship, no compensation",
    body: `Alert Interface is not a broker-dealer or a registered investment adviser, does not hold your funds, and does not receive compensation from any security, issuer, or broker mentioned here.`,
  },
];

export default function DisclosuresPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-16">
      <p className="font-mono text-xs uppercase tracking-[.16em] text-muted-foreground mb-10">
        Disclosures
      </p>

      <div className="space-y-0">
        {sections.map((s, i) => (
          <section key={i} className="border-t border-border py-8">
            <h2 className="text-sm font-semibold text-foreground mb-3">
              {s.heading}
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {s.body}
            </p>
            {s.link && (
              <Link
                href={s.link.href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-sm text-primary hover:underline mt-2 inline-block"
              >
                {s.link.label} ↗
              </Link>
            )}
          </section>
        ))}
      </div>
    </div>
  );
}
