import type { Metadata } from "next";
import DisclosuresTracker from "./tracker";

export const metadata: Metadata = {
  title: "Disclosures | Alert Interface",
};

export default function DisclosuresPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-16">
      <DisclosuresTracker />
      <h1 className="text-2xl font-semibold text-foreground">Disclosures</h1>
      <p className="text-sm text-muted-foreground mt-1">
        Last updated September 14, 2026
      </p>

      <section className="mt-8">
        <p className="text-sm leading-normal text-muted-foreground">
          <span className="font-bold text-foreground">1. Not investment advice.</span>{" "}
          Alert Interface is an independent research and educational tool.
          Nothing on this site is personalized investment advice, and nothing
          here considers your financial situation, objectives, or risk
          tolerance. Ivy's picks and Build a Trade drafts are generated by
          software from public data and are published to every visitor
          identically. You alone are responsible for any decision to trade.
        </p>
      </section>

      <section className="mt-8">
        <p className="text-sm leading-normal text-muted-foreground">
          <span className="font-bold text-foreground">2. Hypothetical performance.</span>{" "}
          Ivy's ledger tracks picks that were generated and recorded but never
          executed. Settled and open P&L are computed from published option
          prices at entry and at settlement or the latest mark. They do not
          include commissions, fees, slippage, bid-ask spread costs, assignment,
          or early exercise, and a real trade would not have filled at these
          prices. Hypothetical results have inherent limitations and past
          results do not indicate future results. The ledger began
          September 15, 2026. Picks generated before that date, during
          development, are not published.
        </p>
      </section>

      <section className="mt-8">
        <p className="text-sm leading-normal text-muted-foreground">
          <span className="font-bold text-foreground">3. Options involve substantial risk.</span>{" "}
          Options are not suitable for all investors. You can lose the entire
          amount paid for an option or spread, and some strategies carry
          unlimited risk. Before trading options, read{" "}
          <a
            href="https://www.theocc.com/company-information/documents-and-archives/options-disclosure-document"
            target="_blank"
            rel="noopener noreferrer"
            className="underline"
          >
            Characteristics and Risks of Standardized Options
          </a>
          , published by the Options Clearing Corporation.
        </p>
      </section>

      <section className="mt-8">
        <p className="text-sm leading-normal text-muted-foreground">
          <span className="font-bold text-foreground">4. Data and AI-generated content.</span>{" "}
          Price and option data come from third-party providers and may be
          delayed, incomplete, or wrong. Reference data (earnings history,
          analyst actions, volatility) refreshes nightly. Research notes are
          written by an AI model and checked by a second model against source
          filings; the check reduces errors but does not eliminate them. Verify
          anything material against the primary source.
        </p>
      </section>

      <section className="mt-8">
        <p className="text-sm leading-normal text-muted-foreground">
          <span className="font-bold text-foreground">5. No relationship, no compensation.</span>{" "}
          Alert Interface is not a broker-dealer or a registered investment
          adviser, does not hold your funds, and does not receive compensation
          from any security, issuer, or broker mentioned here.
        </p>
      </section>

      <p className="text-xs text-muted-foreground/60 mt-12">
        These disclosures apply to all pages on alertinterface.com.
      </p>
    </div>
  );
}
